import Head from "next/head";
import Banner from "../components/Banner/Banner";
import Navbar from "../components/Navbar/Navbar";
import SectionCards from "../components/Card/SectionCards";
import styles from "../styles/Home.module.css";
import { getPopularVideos, getVideos } from "../components/lib/videos";
import Cookies from "js-cookie";
import Link from "next/link";
import { useEffect, useState } from "react";


export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("Productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();
  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos },
  };
}

export default function Home({
  disneyVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
}) {
  const [userEmail, setUserEmail] = useState();

  useEffect(() => {
    const getTokenAndFetchEmail = async () => {
      const token = Cookies.get("netflix-cookie-token");

      console.log(token);

      const res1 = await fetch("http://localhost:7999", {
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          "x-access-token": token,
        },
      });

      const { email } = await res1.json();
      // const resJson = JSON.parse(resText);
      
      setUserEmail(email)
      console.log("email", email);
    };

    getTokenAndFetchEmail();
  }, []);

  if (userEmail === "") {
    return <Link href="/login">Login</Link>;
  }

  console.log("userEmail => ",userEmail);


  return userEmail  ? (
    <center>
      <h1>
        <Link href="/login">Login</Link>
      </h1>
    </center>
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Navbar userEmail={userEmail} />
        <Banner
          videoId="4zH5iYM4wJo"
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/reddog.webp"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
