import Head from "next/head";
import Banner from "../components/Banner/Banner";
import Navbar from "../components/Navbar/Navbar";
import SectionCards from "../components/Card/SectionCards";
import styles from "../styles/Home.module.css";
import { getVideos } from "../components/lib/videos";

export default function Home() {

  // const disneyVideos = [
  //   {
  //     imgUrl : "/static/reddog.webp"
  //   },
  //   {
  //     imgUrl : "/static/reddog.webp"
  //   },
  //   {
  //     imgUrl : "/static/reddog.webp"
  //   },
  // ]

  const disneyVideos = getVideos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username="jhasundarm@gmail.com" />
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/reddog.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large"/>
        <SectionCards title="Productivity" videos={disneyVideos} size="medium"/>
        <SectionCards title="Watch it again" videos={disneyVideos} size="small"/>
      </div>

      {/* <Card  size="medium"/>
      <Card imgUrl="/static/reddog.webp" size="small"/> */}
    </div>
  );
}
