import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Navbar from '../components/Navbar/Navbar'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username="jhasundarm@gmail.com"/>
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/reddog.webp"
      />
    </div>
  )
}
